### ISSUE TITLE
storage-migration cleanup: remove delay from update-catalog step robot

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_robots#277]
Assuming there are no issues between newly ingested content (pres-robots) and getting said content into preservation-catalog (pres-cat workers), then we are ready for this cleanup.  (e.g. after 10/10)

On the final preservation storage migration to ceph style storage, we had a bunch of problems*, and one way around them was to introduce a delay before executing the update-catalog step.

This ticket is about removing that no-longer-necessary delay:
- [x] from pres_robots code (it was introduced in PR #269 and PR #270)
- [x] from shared_configs (qa, stage, prod)

As of this morning, that delay has been set to 0 seconds in shared_configs.

------
* background for the curious

Julian and John detected the problem was that even though files were written to Ceph, they weren't immediately readable by anything -- there was a file locking problem that meant the files were invisible to ?? any VM but the original writer ?? ... and we could only get the lock to release by rebooting MDS (Meta-Data Service) on Ceph storage.

Julian ultimately found a way to configure MDS to work better for us.

**Comment by ndushay** [comment]
@jmartin-sul is this still something we should do?

**Comment by ndushay** [comment]
If this is done, be sure to watch for errors increasing or decreasing with this change (honeybadger?   Andrew have any ideas for how to track this?)

**Comment by jmartin-sul** [comment]
i would somewhat de-prioritize this for now, just because we've recently run into some issues where adding back an artificial delay might ease write/read contention between different VMs that all talk to Ceph (see [this slack thread](https://stanfordlib.slack.com/archives/C0RK5EM9N/p1658257751285239)).

however, i'm hopeful that we can get rid of it eventually, especially since the delay time is currently set to zero, effectively making this a no-op.

per the linked slack thread, we've identified a more promising place for adding a hacky delay to ameliorate our most recent read/write contention issue: the `validate-moab` step.  will file a ticket about that shortly.

if this ticket is done, this comment in preservation catalog should be updated, as it references code/comment that this ticket would have removed:  https://github.com/sul-dlss/preservation_catalog/blob/4f92f00c7fdc1b074eca4438b3ea7cbe8bb88eee/app/jobs/zipmaker_job.rb#L39-L41

**Comment by ndushay** [comment]
DONE!
